In [12]:
# requires you to install numpy first with 'pip3 install numpy' in terminal
import numpy

data = numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')
print(data)

# print different attributes of the 'data' object just defined 
print(type(data))
print(data.dtype)
print(data.shape)
print('first value in data:', data[0,0])
print('middle value in data:', data[29,19]) # assesses row 30, column 20

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]
<class 'numpy.ndarray'>
float64
(60, 40)
first value in data: 0.0
middle value in data: 16.0


In [17]:
# Slicing data
# select the first 10 colums (days) for the first 4 patients
# 0:4 means start at index 0 and go up to, but not including, 4. 
print('patients 1 through 4:')
print(data[0:4, 0:10])

# 5:10 therefore means, starting from patient 6 to 10, or index 5 to 9 inclusive.
print('patients 6 through 10:')
print(data[5:10, 0:10])

# the following selects rows 0 through 2 and columns 36 to the end 
small = data[:3, 36:]
print('small is:')
print(small)

patients 1 through 4:
[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 2. 0. 4. 2. 2. 1. 6. 7.]]
patients 6 through 10:
[[0. 0. 1. 2. 2. 4. 2. 1. 6. 4.]
 [0. 0. 2. 2. 4. 2. 2. 5. 5. 8.]
 [0. 0. 1. 2. 3. 1. 2. 3. 5. 3.]
 [0. 0. 0. 3. 1. 5. 6. 5. 5. 8.]
 [0. 1. 1. 2. 1. 3. 5. 3. 5. 8.]]
small is:
[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


In [18]:
# Analysing data 

# find the average inflammation for all patients on all days
print(numpy.mean(data))

6.14875


In [20]:
# Example of a function that doesn't have any input/arguments
import time
print(time.ctime())

Fri Oct 18 12:32:07 2024
