In [2]:
# requires you to install numpy first with 'pip3 install numpy' in terminal
# on mac I had to 'conda install numpy' in the conda environment
import numpy

data = numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')
print(data)

# print different attributes of the 'data' object just defined 
print(type(data))
print(data.dtype)
print(data.shape)
print('first value in data:', data[0,0])
print('middle value in data:', data[29,19]) # assesses row 30, column 20

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]
<class 'numpy.ndarray'>
float64
(60, 40)
first value in data: 0.0
middle value in data: 16.0


In [17]:
# Slicing data
# select the first 10 colums (days) for the first 4 patients
# 0:4 means start at index 0 and go up to, but not including, 4. 
print('patients 1 through 4:')
print(data[0:4, 0:10])

# 5:10 therefore means, starting from patient 6 to 10, or index 5 to 9 inclusive.
print('patients 6 through 10:')
print(data[5:10, 0:10])

# the following selects rows 0 through 2 and columns 36 to the end 
small = data[:3, 36:]
print('small is:')
print(small)

patients 1 through 4:
[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 2. 0. 4. 2. 2. 1. 6. 7.]]
patients 6 through 10:
[[0. 0. 1. 2. 2. 4. 2. 1. 6. 4.]
 [0. 0. 2. 2. 4. 2. 2. 5. 5. 8.]
 [0. 0. 1. 2. 3. 1. 2. 3. 5. 3.]
 [0. 0. 0. 3. 1. 5. 6. 5. 5. 8.]
 [0. 1. 1. 2. 1. 3. 5. 3. 5. 8.]]
small is:
[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


In [20]:
# Example of a function that doesn't have any input/arguments
import time
print(time.ctime())

Fri Oct 18 12:32:07 2024


In [12]:
# Analysing data 

# find the average inflammation for all patients on all days
print(numpy.mean(data))

# find maximum, minimum, and standard devation and define them as objects
maxval, minval, stdval = numpy.amax(data), numpy.amin(data), numpy.std(data)
print('maximum inflammation:', maxval)
print('minimum inflammation:', minval)
print('standard deviation:', stdval)

patient_0 = data[0, :] # 0 on the first axis (rows) and everything in the column)
print('maximum inflammation for patient 0:', numpy.amax(patient_0))

# We don't need a row of variables on its own to do that. 
print('maximum inflammation for patient 2:', numpy.amax(data[2, :]))

# Get the maximum inflammation for each patient over all days (average of each row)
print(numpy.mean(data, axis=0)) # axis 0 is the rows 
print(numpy.mean(data, axis=0).shape) # tells us there are 40 averages from 40 rows
print(numpy.mean(data, axis=1))
print(numpy.mean(data, axis=1).shape) # 60 averages from 60 columns

6.14875
maximum inflammation: 20.0
minimum inflammation: 0.0
standard deviation: 4.613833197118566
maximum inflammation for patient 0: 18.0
maximum inflammation for patient 2: 19.0
[ 0.          0.45        1.11666667  1.75        2.43333333  3.15
  3.8         3.88333333  5.23333333  5.51666667  5.95        5.9
  8.35        7.73333333  8.36666667  9.5         9.58333333 10.63333333
 11.56666667 12.35       13.25       11.96666667 11.03333333 10.16666667
 10.          8.66666667  9.15        7.25        7.33333333  6.58333333
  6.06666667  5.95        5.11666667  3.6         3.3         3.56666667
  2.48333333  1.5         1.13333333  0.56666667]
(40,)
[5.45  5.425 6.1   5.9   5.55  6.225 5.975 6.65  6.625 6.525 6.775 5.8
 6.225 5.75  5.225 6.3   6.55  5.7   5.85  6.55  5.775 5.825 6.175 6.1
 5.8   6.425 6.05  6.025 6.175 6.55  6.175 6.35  6.725 6.125 7.075 5.725
 5.925 6.15  6.075 5.75  5.975 5.725 6.3   5.9   6.75  5.925 7.225 6.15
 5.95  6.275 5.7   6.1   6.825 5.975 6.725 5.7   6.

In [17]:
element = 'oxygen'
print(element[0:3]) # first 3 letters of oxygen
print(element[1:-1]) # oxygen with the first and last index removed
print(element[-3:])

oxy
xyge
gen


In [47]:
# Stacking arrays 
import numpy 

A = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('A = ')
print(A)

B = numpy.hstack([A, A])
print('B = ')
print(B)

C = numpy.vstack([A, A])
print('C = ')
print(C)

D = numpy.hstack((A[:, :1], A[:, -1:]))
print('D = ')
print(D)



A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B = 
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
C = 
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]
D = 
[[1 3]
 [4 6]
 [7 9]]


In [55]:
# Change in inflammation 

patient3_week1 = data[3, :7]
print(patient3_week1)
numpy.diff(patient3_week1) # array shorter by one element

# Find the difference for each patient 
all_week1 = data[:,0:7]
print(numpy.diff(all_week1))
numpy.diff(all_week1).shape

# Find the largest difference between days (biggest increase)
numpy.amax(numpy.diff(data, axis=1), axis=1)

# Find the largest difference in magnitude, increase or decrease
numpy.amax(numpy.absolute(numpy.diff(data, axis=1)), axis=1)

[0. 0. 2. 0. 4. 2. 2.]
[[ 0.  1.  2. -2.  1.  2.]
 [ 1.  1. -1.  1. -1.  2.]
 [ 1.  0.  2.  0. -1.  4.]
 [ 0.  2. -2.  4. -2.  0.]
 [ 1.  0.  2.  0. -2.  2.]
 [ 0.  1.  1.  0.  2. -2.]
 [ 0.  2.  0.  2. -2.  0.]
 [ 0.  1.  1.  1. -2.  1.]
 [ 0.  0.  3. -2.  4.  1.]
 [ 1.  0.  1. -1.  2.  2.]
 [ 1. -1.  0.  4. -1.  0.]
 [ 1. -1.  0.  3.  1. -2.]
 [ 0.  2. -1.  3. -1.  3.]
 [ 0.  0.  0.  1.  2. -2.]
 [ 1.  1. -1.  0.  0.  3.]
 [ 1.  0. -1.  1.  1.  2.]
 [ 0.  0.  0.  2.  1.  3.]
 [ 0.  0.  1.  1. -1.  3.]
 [ 0.  2. -1.  1.  3. -1.]
 [ 1.  1. -2.  1.  3. -1.]
 [ 1.  0.  2. -2.  3.  0.]
 [ 0.  2.  1. -1.  1. -1.]
 [ 0.  0.  3.  1.  1. -4.]
 [ 1.  0.  0.  0.  2.  0.]
 [ 1.  0.  0.  1.  1.  2.]
 [ 0.  2. -1.  2.  0. -1.]
 [ 0.  1.  1.  2. -2.  0.]
 [ 0.  1.  0.  0.  4. -4.]
 [ 0.  2.  0.  1.  1.  2.]
 [ 0.  0.  1.  3.  0.  2.]
 [ 1.  0. -1.  3. -1.  2.]
 [ 0.  2.  1.  0.  1.  1.]
 [ 1.  1.  0.  0.  1.  3.]
 [ 0.  2. -1.  2.  2.  1.]
 [ 0.  1.  1.  2. -3.  4.]
 [ 0.  0.  3. -2.  2.  3.]
 [ 1.

array([12., 14., 11., 13., 11., 13., 10., 12., 10., 10., 10., 12., 13.,
       10., 11., 10., 12., 13.,  9., 10., 13.,  9., 12.,  9., 12., 11.,
       10., 13.,  9., 13., 11., 11.,  8., 11., 12., 13.,  9., 10., 13.,
       11., 11., 13., 11., 13., 13., 10.,  9., 10., 10.,  9.,  9., 13.,
       10.,  9., 10., 11., 13., 10., 10., 12.])